# Generated by Django 4.1.7 on 2023-02-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='propert_owner',
            new_name='property_owner',
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.IntegerField(),
        ),
    ]
