# Generated by Django 4.1.7 on 2023-02-20 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_propert_owner_guest_property_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='bookings.property'),
        ),
    ]
