# Generated by Django 4.1.7 on 2023-02-20 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_property_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.address'),
        ),
    ]
