# Generated by Django 4.1.7 on 2023-02-20 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_address_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='bookings.address'),
        ),
    ]
