# Generated by Django 4.1.7 on 2023-02-28 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_property_address_address_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest', to='bookings.contact'),
        ),
        migrations.AlterField(
            model_name='address',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='bookings.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='bookings.contact'),
        ),
    ]
