# Generated by Django 4.1.7 on 2023-02-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_property_guest_alter_address_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='guest',
        ),
        migrations.AddField(
            model_name='property',
            name='guest',
            field=models.ManyToManyField(blank=True, null=True, related_name='guest', to='bookings.contact'),
        ),
    ]
