# Generated by Django 4.1.7 on 2023-03-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_remove_property_guest_property_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='guest',
            new_name='guests',
        ),
    ]
